### ISSUE TITLE
Missing script error

### ISSUE THREAD

**Issue by kaiba-yoha** [keijiro/Smrvfx#33]
質問失礼致します。
プロジェクトでVFXPropertyBinderがついたGameObjectをPrefab化するとSkinnedMeshBinderがMissingScriptになりBindが外れてしまいます。
![image](https://user-images.githubusercontent.com/28562498/141227347-56201b4d-3cfc-4f8d-9c54-470a8532212b.png)
また、Prefab化の際に以下のようなエラーが出ます。
![image](https://user-images.githubusercontent.com/28562498/141227634-bc0c7c9f-5378-471d-a124-ca7f2f44b0cc.png)

環境は以下の通りです。
Unity 2020.3.4f  HDRP 10.4

何か設定のミスによるものでしたら申し訳ありませんが、ご教授いただければ幸いです。

**Comment by keijiro** [comment]
I think you're seeing an old version of the project. Now this repository only contains a project that shows how to use the built-in skinned mesh sampling feature. I'd recommend using the newer approach instead of the old solution.

恐らく古いバージョンを見ていると思われますが、現在このリポジトリは内臓の skinned mesh サンプリング機能の使用方法を提示するプロジェクトのみ含んでいます。古いソリューションよりも新しい機能の方を使うことをお勧めします。
